export default {
  MIN_NAME_CHARS: 2,
  MAX_NAME_CHARS: 30,
  MIN_SURNAME_CHARS: 2,
  MAX_SURNAME_CHARS: 30,
  MIN_USERNAME_CHARS: 2,
  MAX_USERNAME_CHARS: 40,
  MIN_PASSWORD_CHARS: 6,
  MAX_PASSWORD_CHARS: 40,

  MIN_BOOKNAME_CHARS: 1,
  MAX_BOOKNAME_CHARS: 80,
  MIN_AUTHOR_CHARS: 2,
  MAX_AUTHOR_CHARS: 40,
  MIN_BOOKID_CHARS: 2,
  MAX_BOOKID_CHARS: 40,
  MIN_ARTICLE_CHARS: 30,
  MAX_ARTICLE_CHARS: 500,
  MIN_BOOK_RATING: 0,
  MAX_BOOK_RATING: 10,

  MIN_REFRESHTOKEN_CHARS: 5,
  MAX_REFRESHTOKEN_CHARS: 100,

  MIN_QUERYARTICLE_LIMIT: 0,
  MAX_QUERYARTICLE_LIMIT: 1000
}
